Mnist:
  val_size: 0.1
  dataset_output_dir: "../dataset/mnist"

Svhn:
  val_size: 0.1
  dataset_output_dir: "../dataset/svhn"

Mnist_M:
  val_size: 0.1
  dataset_output_dir: "../dataset/mnist_m"

protonet:
  n_way: 5
  k_shot: 5
  q_query: 15
  episodes: 100
  epochs: 200
  in_channels: 3
  hidden_dim: 64
  embedding_dim: 64
  lr: 0.001
  evalute_episodes: 1000

maml:
  n_way: 5
  k_shot: 1
  q_query: 15

  meta_batch_size: 8
  inner_updates: 4
  meta_iterations: 200
  
  in_channels: 3
  hidden_dim: 64
  embedding_dim: 64
  
  alpha: 0.05 #inner lr
  beta: 0.001 #meta lr
  
  # evalute_episodes: 100

protomaml:
  n_way: 5
  k_shot: 1
  q_query: 15

  meta_batch_size: 8
  inner_updates: 4
  meta_iterations: 200
  
  in_channels: 3
  hidden_dim: 64
  embedding_dim: 64
  
  alpha: 0.0054 #inner lr
  beta: 0.001 #meta lr

dann_baseline:
  in_channels: 3
  hidden_dim: 64
  embedding_dim: 64

  batch_size: 512
  num_workers: 0
  lr: 0.001 
  epochs: 100

dann_without_grl:
  in_channels: 3
  hidden_dim: 64
  embedding_dim: 64

  batch_size: 512
  num_workers: 0
  lr: 0.001 
  epochs: 100

dann:
  in_channels: 3
  hidden_dim: 64
  embedding_dim: 64
  batch_size: 512
  num_workers: 0
  lr: 0.001
  epochs: 600

compare_experiments:
  n_way: 5
  ks: [1, 2, 4, 8, 16]
  q_query: 15
  episodes: 200

xtra:
  seed: 42
